version: "3.8"               # Версия синтаксиса Docker Compose (можно не указывать)

services:                     # Раздел, где описываются все контейнеры (сервисы)
  web:                        # Имя нашего сервиса (может быть любым)
    image: nginx:latest       # Используем официальный образ nginx
    container_name: my_web    # Назначаем понятное имя контейнеру

    ports:
      - "8080:80"             # Пробрасываем порт 80 из контейнера 
                              # на 8080 на хостовой машине

    volumes:
      - ./mywebsite:/usr/share/nginx/html
                              # Монтируем локальную папку mywebsite
                              # в директорию /usr/share/nginx/html,
                              # откуда nginx раздает статические файлы

    command: nginx -g "daemon off;"
                              # Параметр 'command' позволяет переопределить команду, 
                              # с которой запускается контейнер, вместо той, что задана 
                              # в Dockerfile образа.
                              # В случае с Nginx по умолчанию уже задана команда 
                              # "nginx -g daemon off;", так что переопределение 
                              # не требуется. Если бы вы хотели добавить или изменить 
                              # запуск, можно было бы это сделать здесь.
